In [2]:
import pandas as pd
import numpy as np

In [3]:
"""
    numpy.concatenate()
"""

x = [1, 2, 3]
y = [4, 5, 6]
z = [7, 8, 9]

np.concatenate([x, y, z])
# vstack(): concatenate verticaly
# hstack(): concatenate horizonaly

print(np.vstack([x, y, z]))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
"""
    pandas.concat()
"""

ser1 = pd.Series(['A', 'B', 'C'], index = [1, 2, 3])
ser2 = pd.Series(['D', 'E', 'F'], index = [4, 5, 6])

print(pd.concat([ser1, ser2]))

# Simply concatenate the two Series object


1    A
2    B
3    C
4    D
5    E
6    F
dtype: object


In [12]:
# make_df(): create a DataFrame object
def make_df(cols, ind):
    data = {c: [str(c) + str(i) for i in ind]
           for c in cols}
    
    return pd.DataFrame(data, ind)

print(make_df('ABC', [1, 2]))

    A   B   C
1  A1  B1  C1
2  A2  B2  C2


In [15]:
# Concatenate the two DataFrame objects

df1 = make_df('AB', [1, 2])
df2 = make_df('AB', [3, 4])

print(df1, '\n')
print(df2, '\n')

print(pd.concat([df1, df2]))

    A   B
1  A1  B1
2  A2  B2 

    A   B
3  A3  B3
4  A4  B4 

    A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4


In [18]:
df3 = make_df('AB', [0, 1])
df4 = make_df('CD', [0, 1])

print(df3, '\n')
print(df4, '\n')

print(pd.concat([df3, df4], axis=1))

    A   B
0  A0  B0
1  A1  B1 

    C   D
0  C0  D0
1  C1  D1 

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1


In [23]:
"""
    concat() Features
"""

# Case 1: Duplicate indices
x = make_df('AB', [0, 1])
y = make_df('AB', [2, 3])

y.index = x.index

print(x, '\n')
print(y, '\n')

print(pd.concat([x, y]))

    A   B
0  A0  B0
1  A1  B1 

    A   B
0  A2  B2
1  A3  B3 

    A   B
0  A0  B0
1  A1  B1
0  A2  B2
1  A3  B3


In [26]:
# Case 2: Catching duplications as errors

try:
    pd.concat([x, y], verify_integrity=True)
    
except ValueError as e:
    print("ValueError: ", e)

ValueError:  Indexes have overlapping values: Int64Index([0, 1], dtype='int64')


In [29]:
# Case 3: Ignore the index:

print(pd.concat([x, y], ignore_index=True))

    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3


In [30]:
# Case 4: Adding multiindex keys (hierachical indexing)


In [33]:
"""
    concat(): join options
"""

x = make_df('ABC', [1, 2])
y = make_df('BCD', [3, 4])

# default: outer join -> union

print(x, '\n')
print(y, '\n')

print(pd.concat([x, y], join='inner'))

    A   B   C
1  A1  B1  C1
2  A2  B2  C2 

    B   C   D
3  B3  C3  D3
4  B4  C4  D4 

    B   C
1  B1  C1
2  B2  C2
3  B3  C3
4  B4  C4


In [34]:
# inner join -> intersection


In [35]:
# oppned()


In [37]:
"""
    join operations
"""

# Prepare for two DataFrame objects
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
                   'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})

df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
                   'hire_data': [2004, 2008, 2012, 2014]})

print(df1, '\n')
print(df2, '\n')

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR 

  employee  hire_data
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014 



In [39]:
# One-to-one joins

df3 = pd.merge(df1, df2)
print(df3)


  employee        group  hire_data
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014


In [43]:
# Many-to-one joins
df4 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],
                   'supervisor': ['Carly', 'Guido', 'Steve']})

print(df3, '\n')
print(df4, '\n')

print(pd.merge(df3, df4)) # df3 = left, df4 = right 

  employee        group  hire_data
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014 

         group supervisor
0   Accounting      Carly
1  Engineering      Guido
2           HR      Steve 

  employee        group  hire_data supervisor
0      Bob   Accounting       2008      Carly
1     Jake  Engineering       2012      Guido
2     Lisa  Engineering       2004      Guido
3      Sue           HR       2014      Steve


In [46]:
# Many=to-many joins

df5 = pd.DataFrame({'group':['Accounting', 'Accounting',
                            'Engineering', 'Engineering',
                            'HR', 'HR'],
                   'skills': ['math', 'spreadsheets', 'coding',
                             'linux', 'spreasheets', 'organization']})

print(df1, '\n')
print(df5, '\n')

print(pd.merge(df1, df5))

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR 

         group        skills
0   Accounting          math
1   Accounting  spreadsheets
2  Engineering        coding
3  Engineering         linux
4           HR   spreasheets
5           HR  organization 

  employee        group        skills
0      Bob   Accounting          math
1      Bob   Accounting  spreadsheets
2     Jake  Engineering        coding
3     Jake  Engineering         linux
4     Lisa  Engineering        coding
5     Lisa  Engineering         linux
6      Sue           HR   spreasheets
7      Sue           HR  organization


In [53]:
"""
    Specifying the merge Key
"""

# 'on' argument: use a common column as merge key

print(df1, '\n')
print(df2, '\n')

df1['age'] = pd.Series([20, 42, 37, 25])
df2['age'] = pd.Series([37, 20, 42, 25])

print(df1, '\n')
print(df2, '\n')

print(pd.merge(df1, df2, on='age'))

  employee        group  age
0      Bob   Accounting   20
1     Jake  Engineering   42
2     Lisa  Engineering   37
3      Sue           HR   25 

  employee  hire_data  age
0     Lisa       2004   37
1      Bob       2008   20
2     Jake       2012   42
3      Sue       2014   25 

  employee        group  age
0      Bob   Accounting   20
1     Jake  Engineering   42
2     Lisa  Engineering   37
3      Sue           HR   25 

  employee  hire_data  age
0     Lisa       2004   37
1      Bob       2008   20
2     Jake       2012   42
3      Sue       2014   25 

  employee_x        group  age employee_y  hire_data
0        Bob   Accounting   20        Bob       2008
1       Jake  Engineering   42       Jake       2012
2       Lisa  Engineering   37       Lisa       2004
3        Sue           HR   25        Sue       2014


In [56]:
# 'left_on' and 'right_on' arguments:

df3 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                   'salary': [70000, 80000, 120000, 90000]})

print(df1, '\n')
print(df3, '\n')

print(pd.merge(df1, df3, left_on='employee', right_on='name'))

  employee        group  age
0      Bob   Accounting   20
1     Jake  Engineering   42
2     Lisa  Engineering   37
3      Sue           HR   25 

   name  salary
0   Bob   70000
1  Jake   80000
2  Lisa  120000
3   Sue   90000 

  employee        group  age  name  salary
0      Bob   Accounting   20   Bob   70000
1     Jake  Engineering   42  Jake   80000
2     Lisa  Engineering   37  Lisa  120000
3      Sue           HR   25   Sue   90000


In [57]:
# 'left_index' and 'right_index' arguments


In [61]:
print(df1, '\n')
print(df2, '\n')

df1a = df1.set_index('employee')
df2a = df2.set_index('employee')

print(df1, '\n')
print(df2, '\n')

print(pd.merge(df1a, df2a, left_index=True, right_index=True))

  employee        group  age
0      Bob   Accounting   20
1     Jake  Engineering   42
2     Lisa  Engineering   37
3      Sue           HR   25 

  employee  hire_data  age
0     Lisa       2004   37
1      Bob       2008   20
2     Jake       2012   42
3      Sue       2014   25 

  employee        group  age
0      Bob   Accounting   20
1     Jake  Engineering   42
2     Lisa  Engineering   37
3      Sue           HR   25 

  employee  hire_data  age
0     Lisa       2004   37
1      Bob       2008   20
2     Jake       2012   42
3      Sue       2014   25 

                group  age_x  hire_data  age_y
employee                                      
Bob        Accounting     20       2008     20
Jake      Engineering     42       2012     42
Lisa      Engineering     37       2004     37
Sue                HR     25       2014     25
